---
name: NPM Audit

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true

permissions: write-all

jobs:
  Auditor:
    name: NPM Audit
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: "npm"
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          scope: "{{ github.repository.owner }}"
      - name: Upgrade to npm@8
        run: npm install -g npm@8
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: NPM Audit
        continue-on-error: true # This should be removed as soon as dev have fixed existing dependency issues.
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: ${{ github.event.assignees }}
          issue_labels: vulnerability, test
          dedupe_issues: true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
