---
name: Python Formatting

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Formatting:
    name: Run formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: python -m pip install -r requirements.txt

      - name: Format with yapf (pep8) and commit back
        run: |
          python -m yapf --style pep8 --recursive -i .
          git diff
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git diff --quiet || (git add -A && git commit -m "Python format")
          git push
